### ISSUE TITLE
The "No module named 'facebook.adobjects'" error when trying to import facebookads module v2.6.0.

### ISSUE THREAD

**Issue by nouvak** [facebook/facebook-python-ads-sdk#169]
Hello!

Thoday I successfully installed the facebookads library to my virtual environment.
Unfortunately, when trying to import the facebookads module, I get the following error:

`ImportError: Failed to import test module: common.sources.tests.test_integration_facebook
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/app/k1/common/sources/tests/test_integration_facebook.py", line 4, in <module>
    from common.sources import facebook
  File "/app/k1/common/sources/facebook.py", line 2, in <module>
    from facebookads import FacebookSession, FacebookAdsApi
  File "/usr/local/lib/python3.5/site-packages/facebookads/__init__.py", line 22, in <module>
    from facebookads.api import FacebookAdsApi
  File "/usr/local/lib/python3.5/site-packages/facebookads/api.py", line 42, in <module>
    from facebookads.adobjects.objectparser import ObjectParser
ImportError: No module named 'facebookads.adobjects'
`

I checked the "/python3.5/site-packages/facebookads" directory and the "adobjects" directory is actualy missing, there are only two subdirectories there "test" and "utils".

Could the issue be in the "setup.py" file, in the line below?
`
PACKAGES = ['facebookads', 'facebookads.test', 'facebookads.utils']
`

It looks to me as if the 'facebookads.utils' package is missing...

Thank you for the info.
  Marko Novak

**Comment by rituparnamukherjee** [comment]
@nouvak 

Thanks for pointing this out. Will have the fix out in a few hours.

**Comment by nouvak** [comment]
My pleasure. :)

**Comment by rituparnamukherjee** [comment]
@nouvak 

Have pushed the fix for this :)
