### ISSUE TITLE
Delete users from Custom Audience error

### ISSUE THREAD

**Issue by psugimoto** [facebook/facebook-python-ads-sdk#279]
I'm trying to update a Custom Audience via API and the method to add_users works fine. The code is somethind like: 
audience.add_users(schema, users, is_raw=True)

However, when I try to use the same parameters to remove_users I get the following error:
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

**Comment by pandasyr** [comment]
Hi @psugimoto ,

Thanks for reporting the issue! Broken pipe sounds like a network issue. Do you have code snippet and/or full stack trace?

**Comment by psugimoto** [comment]
Hello pandasyr,

Thanks for the the fast response. This issue in consistent, I've never been able to remove_users although add_users is working fine. The code I'm using is very simple:
```python
schema1 = [CustomAudience.Schema.MultiKeySchema.phone,
           CustomAudience.Schema.MultiKeySchema.email]
audience.remove_users(schema1, users.fillna('')[['phone_number', 'email']].values.tolist(), is_raw=True)
```
where users is a pandas dataframe of users.

The traceback is the following:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/usr/local/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/local/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 334, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/usr/local/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/local/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/tasks.py", line 200, in logger_wrapped_function
    return f(*args, **kwargs)
  File "/app/tasks_functions.py", line 476, in facebook_audience_update
    fb.update_pro_audiences()
  File "/app/facebook/client.py", line 394, in update_pro_audiences
    audience.remove_users(schema1, users.fillna('')[['phone_number', 'email']].values.tolist(), is_raw=True)
  File "/usr/local/lib/python3.5/site-packages/facebookads/adobjects/helpers/customaudiencemixin.py", line 225, in remove_users
    pre_hashed,
  File "/usr/local/lib/python3.5/site-packages/facebookads/api.py", line 301, in call
    files=files,
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
Process Process-3:1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/usr/local/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/local/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 334, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/usr/local/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/local/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/app/tasks.py", line 69, in async_task
    function(*args, **kwargs)
  File "/app/tasks.py", line 203, in logger_wrapped_function
    raise e
  File "/app/tasks.py", line 200, in logger_wrapped_function
    return f(*args, **kwargs)
  File "/app/tasks_functions.py", line 476, in facebook_audience_update
    fb.update_pro_audiences()
  File "/app/facebook/client.py", line 394, in update_pro_audiences
    audience.remove_users(schema1, users.fillna('')[['phone_number', 'email']].values.tolist(), is_raw=True)
  File "/usr/local/lib/python3.5/site-packages/facebookads/adobjects/helpers/customaudiencemixin.py", line 225, in remove_users
    pre_hashed,
  File "/usr/local/lib/python3.5/site-packages/facebookads/api.py", line 301, in call
    files=files,
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
1
Traceback (most recent call last):
  File "/app/tasks.py", line 89, in run_task
    raise RuntimeError(p.exitcode)
RuntimeError: 1
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/app/tasks.py", line 99, in run_task
    raise e
  File "/app/tasks.py", line 89, in run_task
    raise RuntimeError(p.exitcode)
RuntimeError: 1

```

**Comment by JiamingFB** [comment]
Hi @psugimoto ,

How many users are you trying to upload? Can you check what is the output of `users.fillna('')[['phone_number', 'email']].values.tolist()`

It will also help if you can add a breakpoint at customaudiencemixin.py line 121 and see what's the value of payload. I feel that either the payload is malformed, contains invalid characters, or maybe the payload is too big for server to handle, for which you can upload users in smaller batches in separate requests.

**Comment by psugimoto** [comment]
Hello @JiamingFB,

I've been trying with ~50k users but it was not working, I've tried now with 20 and it went fine . The payload shouldn't be the problem since I can use the same arguments to add_users. So, there's is a difference between the size of the payload allowed to add_users and to remove_users ? I've added all the users successfully with one API call before.

**Comment by JiamingFB** [comment]
Hi @psugimoto ,

Yes, there is a big difference. add_users() is a HTTP POST call and the payload data (users) is in the request body, which means you can send large data without problem. However, remove_users() is a DELETE call, which encodes the payload data (users) in the URI, and therefore there is a size limit.

**Comment by psugimoto** [comment]
Thanks @JiamingFB !
