### ISSUE TITLE
Unit tests fail at the HEAD: facebookads.objects is deprecated

### ISSUE THREAD

**Issue by uppercasebrands** [facebook/facebook-python-ads-sdk#304]
python -m facebookads.test.unit

returns:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/user/facebook-python-ads-sdk/facebookads/test/unit.py", line 37, in <module>
    from .. import objects
ImportError: cannot import name objects

**Comment by hueanhpt** [comment]
You can try facebookads.abobjects

**Comment by daphyFB** [comment]
The fix #305 has been merged.
