### ISSUE TITLE
`get_ad_creatives` failing with `BadStatusLine`

### ISSUE THREAD

**Issue by jthomm** [facebook/facebook-python-ads-sdk#324]
Our script is failing intermittently with `BadStatusLine` while calling `get_ad_creatives`.  This behavior has been persistent since Saturday (4/29) morning ET.  When we restart the script, it usually succeeds on the next attempt.  However it later fails with the same error on a different API call.

Here's an example request:

```
[2017-05-01 17:06:45 requests.packages.urllib3.connectionpool DEBUG  ] "GET /v2.8/6038882249874/adcreatives?access_token=<ACCESS_TOKEN_REMOVED>&appsecret_proof=<APP_SECRET_PROOF_REMOVED>&fields=id%2Cname%2Cadlabels%2Capplink_treatment%2Cbody%2Ccall_to_action_type%2Ceffective_instagram_story_id%2Ceffective_object_story_id%2Cimage_crops%2Cimage_hash%2Cimage_url%2Cinstagram_actor_id%2Cinstagram_permalink_url%2Cinstagram_story_id%2Clink_og_id%2Clink_url%2Cobject_id%2Cobject_type%2Cobject_url%2Cplatform_customizations%2Cproduct_set_id%2Crun_status%2Ctemplate_url%2Cthumbnail_url%2Ctitle%2Curl_tags%2Cuse_page_actor_override%2Caction_spec%2Ccall_to_action%2Cdynamic_ad_voice%2Cfollow_redirect%2Cimage_file%2Cobject_instagram_id%2Cvideo_id%2Cobject_story_id%2Cobject_story_spec&summary=true HTTP/1.1" 200 815
Traceback (most recent call last):
  File "fetch_ad_creatives.py", line 203, in <module>
    for ad in generate_ads(initialize_ad_user())
  File "Marketing/lib/python2.7/site-packages/backports/csv.py", line 207, in writerows
    for row in rows:
  File "fetch_ad_creatives.py", line 204, in <genexpr>
    for ad_creative_dict in ad.get_ad_creatives(ad_creative_fields))
  File "Marketing/lib/python2.7/site-packages/facebookads/adobjects/ad.py", line 258, in get_ad_creatives
    return request.execute()
  File "Marketing/lib/python2.7/site-packages/facebookads/api.py", line 648, in execute
    cursor.load_next_page()
  File "Marketing/lib/python2.7/site-packages/facebookads/api.py", line 792, in load_next_page
    params=self.params,
  File "Marketing/lib/python2.7/site-packages/facebookads/api.py", line 301, in call
    files=files,
  File "Marketing/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "Marketing/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "Marketing/lib/python2.7/site-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Is there anything in the library that can handle retrying a request that fails with `BadStatusLine` or do we need to implement retry in our script?  Do we know why this is suddenly failing?  We've been using this script daily for many months without hitting this.

**Comment by jthomm** [comment]
I think I understand why this is happening.  About 15 minutes in, the persistent connection with graph.facebook.com is getting terminated.  The next time `FacebookAdsApi` makes an HTTP request using this connection, it fails with `BadStatusLine`.

To handle this, I wrap `FacebookAdsApi.call` in a retry decorator after I instantiate it:

```py
facebook_ads_api = FacebookAdsApi(facebook_session)
facebook_ads_api.call = my_retry_decorator(facebook_ads_api.call)
```

(The decorator I'm using is from [this great library](https://github.com/rholder/retrying) if anyone is interested.)
