### ISSUE TITLE
Getting error " Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it"

### ISSUE THREAD

**Issue by vikaschauhan123** [facebook/facebook-python-ads-sdk#353]
For past few months the code run properly but now getting error message. and when i run this same code on other machine is works fine.  but on my machine is gives error.
How to reslove this: 
I am using this method:-
me = AdUser(fbid='me')
my_account = me.get_ad_accounts()[0]
and i am getting error 
 Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PythonWorkspace\audience.py", line 36, in <module>
    account_id = me.get_ad_accounts()
  File "C:\Python27\lib\site-packages\facebookads\adobjects\helpers\adaccountusermixin.py", line 55, in get_ad_accounts
    return self.iterate_edge(AdAccount, fields, params, endpoint='adaccounts')
  File "C:\Python27\lib\site-packages\facebookads\adobjects\abstractcrudobject.py", line 542, in iterate_edge
    cursor.load_next_page()
  File "C:\Python27\lib\site-packages\facebookads\api.py", line 792, in load_next_page
    params=self.params,
  File "C:\Python27\lib\site-packages\facebookads\api.py", line 301, in call
    files=files,
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
```

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues!
Since the code worked on your other machine, this is very unlikely SDK issues. I'd suggest you to check your certificate, firewall, routers, and/or any other network settings on your original machines. Thanks!
